[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = false
include = '\.pyi?
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["cyber"]

# Added Flake8 configuration
[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"] # E203 is often ignored to avoid conflicts with Black's formatting
# exclude = [".git", "__pycache__", "build", "dist"]
# max-complexity = 10
# docstring-convention = "google" # if using pydocstyle and Google style
